// Shared across every Layer 3 scaffold builder (cli/src/scaffold/*.ts) —
// the parts that don't vary by framework: hashing/collecting vendored files
// for the customization-guard manifest (docs/layer2-layer3-plan.md, Subject
// 2, "the ACIM lesson"), copying this pipeline's own agent-facing docs into
// a freshly scaffolded project, and turning already-fetched font files
// (promote's own --fonts-dir convention, see font-slug.ts) into real
// @font-face rules. First extracted from scaffold/nextjs.ts when the Vue
// scaffold builders needed the exact same logic — see "reuse over reinvent"
// in pipeline-plan.md.

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, copyFileSync } from "node:fs";
import { join } from "node:path";

import { slugFont, FONT_WEIGHTS } from "./font-slug.ts";

export const AGENT_DOC_FILES = ["AGENTS.md", "foundations-rules.md", "design.md"];

export function hashFile(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

export function collectFilesRecursive(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...collectFilesRecursive(full));
    else out.push(full);
  }
  return out;
}

export function copyAgentDocs(codeDir: string, outDir: string): string[] {
  const written: string[] = [];
  for (const file of AGENT_DOC_FILES) {
    const src = join(codeDir, file);
    if (!existsSync(src)) continue;
    copyFileSync(src, join(outDir, file));
    written.push(file);
  }
  return written;
}

// Tailwind's own platform (generate/tailwind.ts) names this token
// --typography-primitive-fontFamily-primary (camelCase path segment,
// untouched by the ramp-relabel transform) — different from the plain CSS
// platform below, verified by actually diffing the two real outputs, not
// assumed to match.
export function parseFontFamiliesFromTailwindCss(themeCss: string): { primary: string; secondary?: string } {
  const primaryMatch = themeCss.match(/--typography-primitive-fontFamily-primary:\s*([^;]+);/);
  const secondaryMatch = themeCss.match(/--typography-primitive-fontFamily-secondary:\s*([^;]+);/);
  if (!primaryMatch) {
    throw new Error("theme.css has no --typography-primitive-fontFamily-primary — was it generated by this pipeline?");
  }
  return { primary: primaryMatch[1].trim(), secondary: secondaryMatch?.[1]?.trim() };
}

// The plain CSS platform (generate/index.ts, always written regardless of
// which platform flags were passed) uses Style Dictionary's standard kebab
// transform on every path segment, so the SAME token comes out as
// --typography-primitive-font-family-primary (dashed) here — confirmed by
// inspecting a real generate run's css/tokens.css, not assumed to match
// tailwind.ts's own naming. Platforms with no dedicated typography output
// of their own (Vuetify's theme.ts is colors-only) fall back to this file
// for font family names instead.
export function parseFontFamiliesFromPlainCss(tokensCss: string): { primary: string; secondary?: string } {
  const primaryMatch = tokensCss.match(/--typography-primitive-font-family-primary:\s*([^;]+);/);
  const secondaryMatch = tokensCss.match(/--typography-primitive-font-family-secondary:\s*([^;]+);/);
  if (!primaryMatch) {
    throw new Error("tokens.css has no --typography-primitive-font-family-primary — was it generated by this pipeline?");
  }
  return { primary: primaryMatch[1].trim(), secondary: secondaryMatch?.[1]?.trim() };
}

// Builds @font-face rules for whichever families actually have real font
// files sitting in fontsDir (same files/naming convention promote's own
// --fonts-dir already uses — see font-slug.ts). Not fatal if a family's
// files are missing, or fontsDir wasn't passed at all: skipped silently,
// same "degrades to a system-font fallback" precedent as promote's
// report.html. Framework-agnostic — publicFontsDir is just wherever that
// framework's static dir lives (Next.js's public/fonts, Vite's public/fonts
// — both served from site root the same way).
export function buildFontFaces(
  families: { primary: string; secondary?: string },
  fontsDir: string | undefined,
  publicFontsDir: string,
): { css: string; filesWritten: string[] } {
  if (!fontsDir) return { css: "", filesWritten: [] };

  const uniqueFamilies = new Map<string, string>(); // slug -> raw (already-quoted-if-needed) literal
  const primaryUnquoted = families.primary.replace(/^['"]|['"]$/g, "");
  uniqueFamilies.set(slugFont(primaryUnquoted), families.primary);
  if (families.secondary) {
    const secondaryUnquoted = families.secondary.replace(/^['"]|['"]$/g, "");
    uniqueFamilies.set(slugFont(secondaryUnquoted), families.secondary);
  }

  const rules: string[] = [];
  const filesWritten: string[] = [];
  for (const [slug, rawFamily] of uniqueFamilies) {
    for (const weight of FONT_WEIGHTS) {
      const srcPath = join(fontsDir, `${slug}-${weight}.woff2`);
      if (!existsSync(srcPath)) continue;
      const fileName = `${slug}-${weight}.woff2`;
      mkdirSync(publicFontsDir, { recursive: true });
      copyFileSync(srcPath, join(publicFontsDir, fileName));
      filesWritten.push(join("public", "fonts", fileName));
      rules.push(
        [
          "@font-face {",
          `  font-family: ${rawFamily};`,
          `  src: url('/fonts/${fileName}') format('woff2');`,
          `  font-weight: ${weight};`,
          "  font-style: normal;",
          "  font-display: swap;",
          "}",
        ].join("\n"),
      );
    }
  }
  return { css: rules.join("\n\n"), filesWritten };
}
