// MD2/MUI generator (MUI, Vuetify, RN Paper — see pipeline-plan.md,
// "Generators"). Reads the DTCG token spec directly, like bootstrap.ts,
// rather than running it through Style Dictionary: the ramp relabel here is
// a small, fully-enumerable table across exactly 3 primitive groups, and
// the derived palette needs real per-value math (see mui-color.ts) that
// doesn't fit Style Dictionary's per-token transform model any better than
// just computing it directly would.
//
// Decided scope (contracts-and-seeds.md, "Positional relabel";
// pipeline-plan.md, "Generators"):
// - Positional relabel of the primitive ramp's step keys onto MUI's native
//   `50`-`900` numbering (our `1100` step has no MUI equivalent and is
//   dropped, same as Tailwind's relabel leaves `static`/`status` alone).
// - Derive `main`/`light`/`dark`/`contrastText` per color group from the
//   semantic layer's base color plus the `static` white/black primitives —
//   using MUI's own real derivation formula (verified from source, see
//   mui-color.ts), not an invented approximation.
// - `status.*` maps onto MUI's own error/warning/info/success color
//   groups (role `5`, "promo," has no MUI slot and is skipped — same
//   treatment as Bootstrap's `$danger`/`$success`/`$warning`/`$info`).

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { GenerateResult } from "./index.ts";
import { readJson, type ColorPrimitivesFile } from "./read-tokens.ts";
import { augmentColor, type MuiColorGroup } from "./mui-color.ts";

// Per contracts-and-seeds.md, "Positional relabel," MD2 column. `1100` is
// intentionally absent — MD2's native shape stops at `900`.
export const STEP_RELABEL: Record<string, string> = {
  "100": "50",
  "200": "100",
  "300": "200",
  "400": "300",
  "500": "400",
  "600": "500",
  "700": "600",
  "800": "700",
  "900": "800",
  "1000": "900",
};

function relabelRamp(group: Record<string, { $value: string }>): Record<string, string> {
  const relabeled: Record<string, string> = {};
  for (const [step, token] of Object.entries(group)) {
    const muiKey = STEP_RELABEL[step];
    if (muiKey) relabeled[muiKey] = token.$value;
  }
  return relabeled;
}

function tsObjectLiteral(obj: Record<string, string>): string {
  const lines = Object.entries(obj).map(([key, value]) => `  ${key}: "${value}",`);
  return `{\n${lines.join("\n")}\n}`;
}

function tsColorGroupLiteral(group: MuiColorGroup): string {
  return `{ main: "${group.main}", light: "${group.light}", dark: "${group.dark}", contrastText: "${group.contrastText}" }`;
}

// Per "Boilerplate status-color formula": role 1=error, 2=success,
// 3=warning, 4=info, 5=promo. Promo has no MUI palette slot and is
// deliberately omitted, not approximated — same as Bootstrap's treatment.
export const STATUS_ROLE_TO_MUI: Record<string, string> = {
  "1": "error",
  "2": "success",
  "3": "warning",
  "4": "info",
};

export function generateMd2(tokensDir: string, outDir: string): GenerateResult {
  const { color } = readJson<ColorPrimitivesFile>(join(tokensDir, "color.primitive.json"));
  const white = color.primitive.static["100"].$value;
  const black = color.primitive.static["200"].$value;

  const buildPath = join(outDir, "mui");
  mkdirSync(buildPath, { recursive: true });
  const filesWritten: string[] = [];

  // --- colors.ts: relabeled primitive ramp, one export per family ---
  const rampExports: string[] = [
    `export const brand = ${tsObjectLiteral(relabelRamp(color.primitive.brand))} as const;`,
  ];
  if (color.primitive["brand-secondary"]) {
    rampExports.push(`export const brandSecondary = ${tsObjectLiteral(relabelRamp(color.primitive["brand-secondary"]))} as const;`);
  }
  rampExports.push(`export const neutral = ${tsObjectLiteral(relabelRamp(color.primitive.neutral))} as const;`);

  const colorsContent = [
    "// Generated by SDSGT — MD2/MUI primitive color ramp.",
    "// Our 100-1100 step numbering relabeled onto MUI's native 50-900 keys",
    "// (our 1100 step has no MUI equivalent and is dropped). Per",
    '// contracts-and-seeds.md, "Positional relabel."',
    "",
    ...rampExports,
    "",
  ].join("\n");
  writeFileSync(join(buildPath, "colors.ts"), colorsContent, "utf-8");
  filesWritten.push("mui/colors.ts");

  // --- palette.ts: derived main/light/dark/contrastText per color group ---
  const paletteEntries: string[] = [`  primary: ${tsColorGroupLiteral(augmentColor(color.primitive.brand["600"].$value, white, black))},`];
  if (color.primitive["brand-secondary"]) {
    paletteEntries.push(`  secondary: ${tsColorGroupLiteral(augmentColor(color.primitive["brand-secondary"]["600"].$value, white, black))},`);
  }
  for (const [role, name] of Object.entries(STATUS_ROLE_TO_MUI)) {
    const token = color.primitive.status[role]?.["200"];
    if (token) paletteEntries.push(`  ${name}: ${tsColorGroupLiteral(augmentColor(token.$value, white, black))},`);
  }

  const paletteContent = [
    "// Generated by SDSGT — MD2/MUI derived palette.",
    "// main/light/dark/contrastText per color group, derived using MUI's own",
    "// real formula (verified from @mui/material source — see",
    "// generate/mui-color.ts): light = lighten(main, 0.2), dark =",
    "// darken(main, 0.3), contrastText picked by WCAG contrast ratio against",
    "// our own static white/black primitives (>= 3:1, MUI's own default",
    "// threshold). Spread this into MUI's createTheme({ palette }).",
    "",
    "export const palette = {",
    ...paletteEntries,
    "} as const;",
    "",
  ].join("\n");
  writeFileSync(join(buildPath, "palette.ts"), paletteContent, "utf-8");
  filesWritten.push("mui/palette.ts");

  return { filesWritten };
}
