// SwiftUI/Xcode scaffold guide — the same resolution as Kotlin's
// (generate/kotlin-scaffold-guide.ts), for the same underlying reason.
//
// Verified 2026-09-14, real research on this actual machine (Xcode 26.4 is
// installed here, so this wasn't guessed from docs alone): there is no
// official, non-interactive way to scaffold a new SwiftUI iOS app project.
// - `xcodebuild -help`'s own real, complete usage list (build, test,
//   archive, export, download platforms/components, resolve package
//   dependencies, etc.) has no project-creation action anywhere in it —
//   confirmed by reading the actual current help output, not assumed.
// - `swift package init --type <type>` is real, but every type
//   (library/executable/tool/build-tool-plugin/command-plugin/macro/empty)
//   is command-line/library-shaped — none produces a real iOS app target
//   (SwiftUI `App` lifecycle, asset catalog, Info.plist, code signing,
//   a scheme Xcode/a simulator can actually launch). This is a cleaner "no"
//   than Kotlin's own `gradle init` finding — Kotlin's tool at least
//   produced SOMETHING (the wrong shape); Swift Package Manager's `init`
//   doesn't attempt an iOS app shape at all.
// - Xcode's own project templates are not exposed through any documented
//   CLI hook — confirmed by checking for the template directory current
//   Xcode versions used to expose (moved/hidden in Xcode 26) and finding
//   no `xcodebuild`/`xcrun` subcommand referencing templates at all. File >
//   New > Project's GUI wizard is the only officially supported path.
//
// One real difference from the Kotlin guide, not just "same idea, new
// platform": generate/swiftui.ts's own DesignTokens.swift is two flat
// `enum { static let ... }` namespaces (Light/Dark) with NO built-in way to
// dynamically switch between them — unlike Compose's ColorScheme (a single
// real object Compose itself switches wholesale) or Vuetify's theme object
// (switched by createVuetify() itself), SwiftUI has no equivalent built-in
// mechanism for a plain enum-of-static-lets. Left as prose instructions,
// every real call site in the user's app would need a manual
// `colorScheme == .dark ? DesignTokens.Dark.x : DesignTokens.Light.x`
// ternary — technically usable, but exactly the kind of "theoretically
// present, not actually usable" gap this project doesn't leave in place
// elsewhere. So this guide ALSO generates a real `Theme.swift` — a standard
// SwiftUI Environment + ViewModifier pattern, with every one of this
// project's own real token names wired in (extracted by reading back the
// already-written DesignTokens.swift content, same "read back what was
// actually written" pattern the Vue.js/React Native/Kotlin guides already
// use for their own conditional exports) — not prose describing a pattern,
// working code implementing it.

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import type { GenerateResult } from "./index.ts";

// Pulls real token names out of DesignTokens.swift's own two enum blocks,
// in the order swiftui.ts's flattenTokens() already wrote them — avoids
// re-traversing the raw semantic token tree a second time just to get the
// same list back.
function extractTokenNames(designTokensSwift: string, namespace: "Light" | "Dark"): string[] {
  const blockMatch = designTokensSwift.match(new RegExp(`enum ${namespace} \\{([\\s\\S]*?)\\n    \\}`));
  if (!blockMatch) return [];
  const names: string[] = [];
  for (const m of blockMatch[1].matchAll(/static let (\w+) =/g)) {
    names.push(m[1]);
  }
  return names;
}

function buildThemeSwift(lightNames: string[], darkNames: string[]): string {
  const hasLight = lightNames.length > 0;
  const hasDark = darkNames.length > 0;
  const names = hasLight ? lightNames : darkNames; // same shape either way — see file header's shared-schema note

  const fields = names.map((n) => `    let ${n}: Color`).join("\n");
  const lightInit = hasLight
    ? [
        "    static let light = Theme(",
        names.map((n) => `        ${n}: DesignTokens.Light.${n}`).join(",\n"),
        "    )",
      ].join("\n")
    : "";
  const darkInit = hasDark
    ? [
        "    static let dark = Theme(",
        names.map((n) => `        ${n}: DesignTokens.Dark.${n}`).join(",\n"),
        "    )",
      ].join("\n")
    : "";

  if (hasLight && hasDark) {
    return [
      "// Generated by SDSGT — dynamic light/dark wrapper around",
      "// DesignTokens.swift's own static enums. Re-run SDSGT's `generate` step",
      "// to update DesignTokens.swift; if your token NAMES ever change (not just",
      "// values), re-run `generate --swiftui` again and re-copy this file too —",
      "// it's generated once, not a live reflection of DesignTokens.swift.",
      "",
      "import SwiftUI",
      "",
      "struct Theme {",
      fields,
      "",
      lightInit,
      "",
      darkInit,
      "}",
      "",
      "private struct ThemeKey: EnvironmentKey {",
      "    static let defaultValue = Theme.light",
      "}",
      "",
      "extension EnvironmentValues {",
      "    var theme: Theme {",
      "        get { self[ThemeKey.self] }",
      "        set { self[ThemeKey.self] = newValue }",
      "    }",
      "}",
      "",
      "extension View {",
      "    /// Call once near the root of your view hierarchy (see",
      "    /// SCAFFOLD_GUIDE.md) to keep `theme` in the environment synced with",
      "    /// the system's light/dark setting.",
      "    func withAppTheme() -> some View {",
      "        modifier(ThemeModifier())",
      "    }",
      "}",
      "",
      "private struct ThemeModifier: ViewModifier {",
      "    @Environment(\\.colorScheme) private var colorScheme",
      "    func body(content: Content) -> some View {",
      "        content.environment(\\.theme, colorScheme == .dark ? .dark : .light)",
      "    }",
      "}",
      "",
    ].join("\n");
  }

  // Single-mode project — no real switching to do, Theme is just a constant.
  const onlyInit = hasLight ? lightInit : darkInit;
  return [
    "// Generated by SDSGT — this project has only one color mode, so Theme is",
    "// a constant rather than an environment-switched value. Re-run SDSGT's",
    "// `generate` step to update DesignTokens.swift; if your token NAMES ever",
    "// change (not just values), re-run `generate --swiftui` and re-copy this",
    "// file too — it's generated once, not a live reflection.",
    "",
    "import SwiftUI",
    "",
    "struct Theme {",
    fields,
    "",
    onlyInit,
    "}",
    "",
    "extension Theme {",
    "    /// This project only has one color mode — `current` always resolves",
    "    /// to it, no environment/colorScheme switching needed.",
    `    static let current = ${hasLight ? "light" : "dark"}`,
    "}",
    "",
  ].join("\n");
}

function buildGuide(hasLight: boolean, hasDark: boolean): string {
  const bothModes = hasLight && hasDark;
  const usageAccess = bothModes ? "@Environment(\\.theme) private var theme" : "";
  const usageExample = bothModes
    ? ["struct ContentView: View {", `    ${usageAccess}`, "", "    var body: some View {", "        Text(\"Hello\")", "            .foregroundColor(theme.actionPrimary)", "    }", "}"].join("\n")
    : ["struct ContentView: View {", "    var body: some View {", "        Text(\"Hello\")", "            .foregroundColor(Theme.current.actionPrimary)", "    }", "}"].join("\n");

  const rootWiring = bothModes
    ? ["@main", "struct MyApp: App {", "    var body: some Scene {", "        WindowGroup {", "            ContentView()", "                .withAppTheme()", "        }", "    }", "}"].join("\n")
    : "No extra root wiring needed — `Theme.current` works anywhere, no environment setup required for a single-mode project.";

  return [
    "# SwiftUI / Xcode — manual scaffold guide",
    "",
    "**Why this is a guide, not an automatic step:** every other framework this",
    "tool supports (Next.js, Vue.js, React Native) has a real official",
    "non-interactive CLI this pipeline drives directly. SwiftUI/Xcode doesn't",
    "have one — verified on a real Xcode 26.4 install, not assumed from docs",
    "alone: `xcodebuild`'s own complete usage list (build/test/archive/",
    "export/download-platform/etc.) has no project-creation action anywhere",
    "in it, `swift package init` has no iOS-app template type at all (only",
    "library/executable/tool/plugin/macro/empty — none of them a real app),",
    "and Xcode's own project templates aren't exposed through any documented",
    "CLI. File > New > Project's GUI wizard is the only officially supported",
    "way to create a new iOS app today. This file exists so that gap doesn't",
    "leave you stuck — every value below is your own real generated data, not",
    "a generic tutorial.",
    "",
    "## 0. Prerequisites",
    "",
    "- [Xcode](https://apps.apple.com/app/xcode/id497799835) installed (from",
    "  the Mac App Store).",
    "",
    "## 1. Create the project",
    "",
    "Open Xcode → **File > New > Project** → **iOS** tab → **App** template",
    "(exact wording may shift slightly between Xcode versions). Interface:",
    "**SwiftUI**. Language: **Swift**. Set your own product name.",
    "",
    "This creates a real project with `<YourAppName>App.swift` (the `@main`",
    "entry point) and `ContentView.swift` already scaffolded — you're about",
    "to add two more files to it.",
    "",
    "## 2. Add your generated token files",
    "",
    "Drag both `DesignTokens.swift` and `Theme.swift` (generated right next",
    "to this file, same `swiftui/` folder) into Xcode's Project Navigator.",
    "**Two checkboxes matter in the dialog that appears — easy to miss both:**",
    "",
    '- **"Copy items if needed"** — check this, or Xcode references the files',
    "  at their original location instead of copying them into your project;",
    "  move or delete the original folder later and your build breaks.",
    "- **Target membership** — make sure your app's target checkbox is",
    "  checked, or the files won't actually compile into your app.",
    "",
    "`DesignTokens.swift` is your resolved semantic color tokens as native",
    "`Color` values, one static namespace per mode you generated",
    "(`DesignTokens.Light`" + (hasDark ? "/`DesignTokens.Dark`" : "") + "). `Theme.swift` wraps " + (bothModes ? "both into a single environment-switched `Theme` that automatically follows the system's light/dark setting" : "it into a `Theme.current` constant") + " — see \"Use it\" below.",
    "",
    "## 3. Use it",
    "",
    "```swift",
    usageExample,
    "```",
    "",
    ...(bothModes
      ? [
          "And once, near your app's root (`<YourAppName>App.swift`), call",
          "`.withAppTheme()` so `theme` stays synced with the system setting:",
          "",
          "```swift",
          rootWiring,
          "```",
          "",
        ]
      : []),
    "## Build it",
    "",
    "Xcode's own **Run** button (▶) builds and launches on a connected",
    "device/simulator. From the command line instead — first see what",
    "destinations are actually available for your scheme (simulator names",
    "and availability change between Xcode versions, so this isn't",
    "hardcoded):",
    "",
    "```",
    "xcodebuild -showdestinations -scheme <YourSchemeName>",
    "```",
    "",
    "then build against one of the real destinations it lists:",
    "",
    "```",
    "xcodebuild -scheme <YourSchemeName> -destination 'platform=iOS Simulator,name=<a name from the list above>' build",
    "```",
    "",
    "## What's in here",
    "",
    "- `DesignTokens.swift` — your generated color tokens. Re-run SDSGT's",
    "  `generate` step to update these; don't hand-edit them directly, since",
    "  the next `generate` run overwrites this file.",
    `- \`Theme.swift\` — ${bothModes ? "the dynamic-switching wrapper" : "the constant wrapper"} described above. Also`,
    "  regenerated by `generate`, but only reflects new token *values*",
    "  automatically — if your token *names* change, re-copy this file too",
    "  (it's generated once from whatever names existed at generation time,",
    "  not a live reflection of `DesignTokens.swift`).",
    "",
  ].join("\n");
}

export function generateSwiftUIScaffoldGuide(outDir: string, designTokensSwiftContent: string): GenerateResult {
  const lightNames = extractTokenNames(designTokensSwiftContent, "Light");
  const darkNames = extractTokenNames(designTokensSwiftContent, "Dark");
  const hasLight = lightNames.length > 0;
  const hasDark = darkNames.length > 0;

  const buildPath = join(outDir, "swiftui");
  writeFileSync(join(buildPath, "Theme.swift"), buildThemeSwift(lightNames, darkNames), "utf-8");
  writeFileSync(join(buildPath, "SCAFFOLD_GUIDE.md"), buildGuide(hasLight, hasDark), "utf-8");

  return { filesWritten: ["swiftui/Theme.swift", "swiftui/SCAFFOLD_GUIDE.md"] };
}
