// Vuetify generator — Layer 2 (see pipeline-plan.md, "Three layers").
// Targets Vuetify 4 (current npm latest, verified 2026-09-10 — Vuetify
// 3.13.0 became the final v3 minor and moved to LTS in July 2026; 4.x is
// now the actively developed line). Verified against Vuetify's own real
// theme composable source (packages/vuetify/src/composables/theme.ts,
// master branch) and its migration notes: the theme system's core
// `ThemeDefinition` shape (`{ dark: boolean, colors: {...} }`) and base
// color keys are unchanged from v3 to v4 — the real breaking changes in v4
// are the default theme mode (system vs light) and elevation moving to
// MD3's 6-level scale, neither of which affects this generator's output
// shape.
//
// Decided scope: like bootstrap.ts, this supplies only the small,
// well-documented custom-theme input contract (primary, secondary,
// background, surface, error, info, success, warning) and lets Vuetify's
// own runtime auto-derive on-*/lighten/darken variants from it — same
// "supply the base, let the framework derive the rest" pattern as
// Bootstrap's own Sass. Vuetify's own DEFAULT theme additionally hardcodes
// a few more keys (surface-bright, primary-darken-1, etc. — confirmed by
// reading the real source) instead of relying purely on auto-derivation,
// but those are Vuetify's own internal implementation choice, not part of
// the documented custom-theme contract this generator targets.
// status.* maps onto Vuetify's native error/warning/info/success color
// keys (role 5, "promo," skipped — same precedent as Bootstrap/MUI's own
// promo-skip, Vuetify has no 5th status slot either).

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { GenerateResult } from "./index.ts";
import { readJson, resolveAlias, type ColorPrimitivesFile, type SemanticFile } from "./read-tokens.ts";
import { LIGHT_FILE, DARK_FILE } from "./index.ts";

// Per "Boilerplate status-color formula": role 1=error, 2=success,
// 3=warning, 4=info, 5=promo. Promo has no Vuetify color slot and is
// deliberately omitted, not approximated — same treatment as Bootstrap/MUI.
export const STATUS_ROLE_TO_VUETIFY: Record<string, string> = {
  "1": "error",
  "2": "success",
  "3": "warning",
  "4": "info",
};

export function resolveSemanticPath(
  semanticFile: string,
  group: string,
  role: string,
  primitives: ColorPrimitivesFile["color"]["primitive"],
): string {
  const { color } = readJson<SemanticFile>(semanticFile);
  const tree = color.semantic as unknown as Record<string, Record<string, { $value: string }>>;
  const raw = tree[group][role].$value;
  return raw.startsWith("{") ? resolveAlias(raw, primitives) : raw;
}

function themeColorsBlock(
  semanticFile: string,
  primitives: ColorPrimitivesFile["color"]["primitive"],
): string {
  const lines: string[] = [
    `      primary: '${primitives.brand["600"].$value}',`,
  ];
  if (primitives["brand-secondary"]) {
    lines.push(`      secondary: '${primitives["brand-secondary"]["600"].$value}',`);
  }
  lines.push(`      background: '${resolveSemanticPath(semanticFile, "background", "primary", primitives)}',`);
  lines.push(`      surface: '${resolveSemanticPath(semanticFile, "background", "surface", primitives)}',`);
  for (const [role, name] of Object.entries(STATUS_ROLE_TO_VUETIFY)) {
    const token = primitives.status[role]?.["200"];
    if (token) lines.push(`      ${name}: '${token.$value}',`);
  }
  return lines.join("\n");
}

export function generateVuetify(tokensDir: string, outDir: string): GenerateResult {
  const { color } = readJson<ColorPrimitivesFile>(join(tokensDir, "color.primitive.json"));
  const primitives = color.primitive;

  const hasLight = existsSync(join(tokensDir, LIGHT_FILE));
  const hasDark = existsSync(join(tokensDir, DARK_FILE));

  const themes: string[] = [];
  if (hasLight) {
    themes.push(
      ["export const lightTheme = {", "  dark: false,", "  colors: {", themeColorsBlock(join(tokensDir, LIGHT_FILE), primitives), "  },", "};"].join("\n"),
    );
  }
  if (hasDark) {
    themes.push(
      ["export const darkTheme = {", "  dark: true,", "  colors: {", themeColorsBlock(join(tokensDir, DARK_FILE), primitives), "  },", "};"].join("\n"),
    );
  }

  const content = [
    "// Generated by SDSGT — Vuetify 4 theme definitions.",
    "// A small, curated base-color set (primary/secondary/background/",
    "// surface/error/info/success/warning) — Vuetify's own runtime derives",
    "// on-*/lighten/darken variants from these, same pattern as Bootstrap's",
    "// own Sass deriving tints from just $primary. Spread into createVuetify",
    "// ({ theme: { themes: { light: lightTheme, dark: darkTheme } } }).",
    "",
    themes.join("\n\n"),
    "",
  ].join("\n");

  const buildPath = join(outDir, "vuetify");
  mkdirSync(buildPath, { recursive: true });
  writeFileSync(join(buildPath, "theme.ts"), content, "utf-8");

  return { filesWritten: ["vuetify/theme.ts"] };
}
